server:
  port: 9091
spring:
  application:
    name: account-biz
mybatis-plus:
  configuration:
    # 设置日志实现类为标准输出日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    root: info